@hostUrl = http://localhost:8080
@accessToken = {{$dotenv ACCESS_TOKEN}}

### create
POST {{hostUrl}}/api/entries
Content-Type: application/json
Authorization: Bearer {{accessToken}}

[]
### get all
GET {{hostUrl}}/api/entries
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### del
DELETE {{hostUrl}}/api/entries/60369fb88ecf5e2a9244b3e1