@hostUrl = http://localhost:8080

### create
POST {{hostUrl}}/feeds
Content-Type: application/json

[{
    "url":"{{$guid}}{{$guid}}{{$guid}}",
    "content": {"something":"{{$randomInt 1 10000000}}"}
},{
    "url":"{{$guid}}{{$guid}}{{$guid}}",
    "content": {"something":"{{$randomInt 1 10000000}}"}
},{
    "url":"{{$guid}}{{$guid}}{{$guid}}",
    "content": {"something":"{{$randomInt 1 10000000}}"}
},{
    "url":"{{$guid}}{{$guid}}{{$guid}}",
    "content": {"something":"{{$randomInt 1 10000000}}"}
}]

### get all
GET {{hostUrl}}/feeds
Authorization: Bearer asdfasdf

### del
DELETE {{hostUrl}}/feeds/6026d68d758eb521dbdfca17